spring.application.name=internal-admin

spring.datasource.url=jdbc:postgresql://localhost:5433/customer-request-db
spring.datasource.username=appuser
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
